/**
 * pages/RecommendationsPage.jsx — /projects/:id/recommendations
 * Phase 2: placeholder shell. Real data: Phase 19 (recommendation engine).
 *
 * Will display (Section 19):
 *   HEURISTIC — Prioritised list: Priority / Category / Problem / Explanation / Action
 */

const priorityColors = {
  HIGH:   'bg-red-500/20    text-red-300    ring-red-500/30',
  MEDIUM: 'bg-amber-500/20  text-amber-300  ring-amber-500/30',
  LOW:    'bg-blue-500/20   text-blue-300   ring-blue-500/30',
}

const exampleRecs = [
  { priority: 'HIGH',   category: 'Complexity',    problem: 'High-complexity functions detected' },
  { priority: 'HIGH',   category: 'Testing',       problem: 'Low automated test coverage' },
  { priority: 'MEDIUM', category: 'Duplication',   problem: 'Repeated code blocks found' },
  { priority: 'LOW',    category: 'Documentation', problem: 'Incomplete API documentation' },
]

export default function RecommendationsPage() {
  return (
    <div className="space-y-6 animate-slide-up">
      <div>
        <h1 className="page-title">Recommendations</h1>
        <p className="page-subtitle">
          Prioritised, rule-based improvements — generated by Phase 19 engine
        </p>
      </div>

      <div className="rounded-lg border border-amber-500/30 bg-amber-500/10
                      px-4 py-3 text-xs text-amber-300">
        ℹ All recommendations are <strong>HEURISTIC</strong> — generated by
        rule-based logic in the scoring engine. They are starting points, not
        definitive diagnoses (Section 19).
      </div>

      {/* Preview of structure (UI only — no real data) */}
      <div className="space-y-3">
        {exampleRecs.map(({ priority, category, problem }, i) => (
          <div key={i} className="card flex items-center gap-4 opacity-30">
            <span className={`badge ring-1 whitespace-nowrap ${priorityColors[priority]}`}>
              {priority}
            </span>
            <div className="flex-1 min-w-0">
              <p className="text-xs font-medium text-slate-400">{category}</p>
              <p className="text-sm text-slate-300 truncate">{problem}</p>
            </div>
            <span className="text-xs text-slate-600 whitespace-nowrap">Phase 19+</span>
          </div>
        ))}
      </div>

      <div className="placeholder-panel">
        <span className="text-3xl">→</span>
        <p className="mt-3 text-sm font-medium text-slate-400">
          Real recommendations generated after analysis completes
        </p>
        <p className="mt-1 text-xs text-slate-600">
          Rule-based engine in <strong className="text-slate-500">Phase 19</strong>
        </p>
      </div>
    </div>
  )
}
